### ISSUE TITLE
A little help please

### ISSUE THREAD

**Issue by djstallion** [angelleye/offers-for-woocommerce#123]
I'm trying to build collection of function.php scripts to turn my WooCommerce temporarily to demo/vacation mode without changing any WooCommerce or Offers For Woocommerce settings. I can remove cart buttons from arhcive and single product pages (offer button will be disabled with cart button in single product page) and also unnneeded tabs, but I can't remove offer button from archive pages.

I tried these hooks but without success:

remove_action( 'woocommerce_after_shop_loop_item', array( $this, 'angelleye_ofwc_after_show_loop_item' ), 99, 2 );

remove_action( 'woocommerce_after_shop_loop_item', 'angelleye_ofwc_after_show_loop_item', 99, 2 );

Can you help me a little? Thank You!

**Comment by angelleye** [comment]
I'm sorry for the delay getting back to you.  I actually didn't see this until I was just now browsing through my issue list.  

For direct support with something like this we'll need you to [purchase at least one hour of premium support](www.angelleye.com/product/premium-support/) to get started.  It could be that we need to add some hooks in our plugin to provide the functionality you're looking for, in which case your support payment would go towards bumping that up as a top priority for an immediate update release.

Alternatively, you may be able to use some CSS to hide the buttons without too much trouble.

Another option would be to simply disable the plugin while you're not using it.  Any settings you've adjusted will remain when you reactivate it.  

I'm going to close this for now, but if I see a premium support order come through for you I'll get back to you right away and we can talk more.

Do feel free to post new issues here in the future if you have bug reports or specific feature requests. Thanks!

**Comment by djstallion** [comment]
I'm definately not going to pay $75 for this. If i test your plugin and helping to found bugs I do it for free. I'm not asking some special feature or something, just a little hook. If you don't want to help, I can live without it.

**Comment by angelleye** [comment]
We do appreciate that, of course.  I didn't mean to imply that we simply wouldn't do this.  It may just have to wait a little longer than if you paid for support.  

On that note, I guess I'm a little confused about what exactly you're after.  Why is it that disabling the plugin and reactivating it when you're ready doesn't work for you?

**Comment by djstallion** [comment]
I have time to wait little longer, that's not problem at all.

I will try to explain more specifically what I wanna to do:
I have working e-shop and I don't have any workers. I am one and only worker. If I'm going to vacation, I have to disable all orders and offers until I'm back from vacation. My solution is collection of scripts in child theme function.php. These scripts are commented out when I don't need vacation mode and I will just uncomment them if I'm going to vacation and I don't have to change any Wordpress, WooCommerce ore some other plugin settings or activity.

Removes offer and enquiry tabs:
add_filter( 'woocommerce_product_tabs', 'woo_remove_product_tabs', 98 );
function woo_remove_product_tabs( $tabs ) {
    unset( $tabs['tab_custom_ofwc_offer'] ); 	// Remove the offer tab
    unset( $tabs['enquiry'] );  		// Remove the enquiry tab
    return $tabs;
}

Removes cart button from archive and single product pages:
remove_action( 'woocommerce_after_shop_loop_item', 'woocommerce_template_loop_add_to_cart' );
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 );

Offer button will be disabled in single product page with the last hook, but it will be still visible in archive pages. I tried to found correct hook to disable also offer button from archive pages, but without success. Maybe I have not enough know-how, but maybe your plugin don't have hooks to do that. There is point when I asked your very tiny help.

I have examined your plugin code and tried these lines, but both of them doesn't work, I don't know why:

remove_action( 'woocommerce_after_shop_loop_item', array( $this, 'angelleye_ofwc_after_show_loop_item' ), 99, 2 );

remove_action( 'woocommerce_after_shop_loop_item', 'angelleye_ofwc_after_show_loop_item', 99, 2 );

Hopefully you can understand now what I'm trying to do and why. This solution is not critical or important, but will be very handy, if I can switch WooCommerce totally to catalog mode only with uncommenting lines in function.php.

**Comment by kcwebmedia** [comment]
@djstallion

The reason those remove_action hooks will not work for you - you cannot 
access the functions called within the private construct function of the 
plugin class; also the plugin does not allow hooks at the current time.

What I suggest is within your theme's functions.php where you have your 
vacation scripts - use the following to activate/deactivate the plugin 
as needed:

Example:

function deactivate_plugin_conditional() {

     if ( 
is_plugin_active('offers-for-woocommerce/offers-for-woocommerce.php') ) {
deactivate_plugins('offers-for-woocommerce/offers-for-woocommerce.php');
     }
}
add_action( 'admin_init', 'deactivate_plugin_conditional' );

function activate_plugin_conditional() {

     if ( 
!is_plugin_active('offers-for-woocommerce/offers-for-woocommerce.php') ) {
activate_plugins('offers-for-woocommerce/offers-for-woocommerce.php');
     }
}
//add_action( 'admin_init', 'activate_plugin_conditional' );

It sounds like you created a script for 'vacation mode' that you comment 
out when not in use -- I also suggest you make a script that reverses 
the vacation mode in order to reactivate plugins you disabled like in 
the example above. Best would be to have one variable you set on or off 
to trigger your scripts.

*Load WP admin, then go view the shop pages and you will see the plugin 
was deactivated. Refresh the WP admin and you'll see the plugin is 
disactivated.

**Comment by djstallion** [comment]
@kcwebmedia, big thanks, I will try Tour suggestions!
