### ISSUE TITLE
Plain text countered offer email link is bad

### ISSUE THREAD

**Issue by kcwebmedia** [angelleye/offers-for-woocommerce#147]
In plain text email template for 'Countered Offer' the link generated to 'pay' is running into the next line of text.

**Comment by angelleye** [comment]
I'm running into a merge conflict when I try to merge this one into dev.  It looks like a pretty simple one to fix.  I see where you said you had used _'s instead of -'s, but it looks like there could be a little bit of both sections that may need to stay..??

Please pull this and then merge the current dev branch into it so you can resolve the conflict for me.
