### ISSUE TITLE
Settings - Offer Expiration

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#22]
Would be nice to provide an option for site owners to set an expiration date on an accepted offer / counter-offer.  

Then we'd need to add logic somewhere to handle this accordingly.  Not sure if we can add some simple if/then logic within a function somewhere or if we'll need to setup a CRON job of some sort to automatically cancel/decline any offers that expired the previous day.

**Comment by kcwebmedia** [comment]
NOTES:
It would not need CRON -- Could just have logic to change status upon buyer attempting to hit an expired offer, AND function to grid/list load of offers so that when admin loads the list it cleans up and mods any expired offers' status to 'expired' or 'trashed'. 
... Best would be to add another offer 'post status' of 'expired offer'.

**Comment by kcwebmedia** [comment]
This issue combines with issue #37
