### ISSUE TITLE
Add apply_filter hook to change the mail id of recipients while sumiting offer form.

### ISSUE THREAD

**Issue by keyurptl** [angelleye/offers-for-woocommerce#259]
In order to manage [offers-for-woocommerce-wc-vendors #4](https://bitbucket.org/angelleye/offers-for-woocommerce-wc-vendors/issues/4/send-offer-email-notifications-to-product)  we need to add apply_filter hook in offers-for-woocommerce plugin while submitting the offer form

**Comment by angelleye** [comment]
@mdrahul Please review the commits that kyurptl submitted and make sure you agree with what was done.

The simple idea here is that we need to be able to filter the email address used when sending out email notifications.

This will be used from our premium extensions like WC Vendors so that notifications can be emailed directly to the vendor instead of the site owner.

**Comment by mdrahul** [comment]
Please consider my last commit as I have modified the code.

**Comment by angelleye** [comment]
@mdrahul Please add a list of the filters that added so here so that I can easily include them in documentation later.  A sample usage snippet would be good, too.

**Comment by mdrahul** [comment]
We have added filter for the recipients "aeofwc_seller_email_address" so that other plugins can add/modify the recipients for the emails sent for new offer and countered offers.
