### ISSUE TITLE
Filters for Make Offer tab and Notes...

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#261]
https://wordpress.org/support/topic/issues-ideas-2/

>Any way to customise the Make Offer tab text to say Price Match, and edit the Offer Notes (optional) to say : Please provide competitor’s website for price match + Any Notes

We just need to add some filter hooks so that people can filter these display values from their theme or plugin files.

**Comment by mdrahul** [comment]
There are already filters available to change the label of the form field. You can check it out in our doc at link: https://www.angelleye.com/offers-for-woocommerce-developer-hooks-guide/

For example, to change the label of "Your Name" you can use the filter called "aeofwc-offer-form-label-your-name". You can have more idea about what is a filter and how to use it at link: https://developer.wordpress.org/reference/functions/apply_filters/

**Comment by mdrahul** [comment]
Hi Andrew,

I have applied few changes regarding filters. I have replaced all dash('-') with underscore('_') in existing filters. 

I have also added following new filters:
1. woocommerce_make_offer_form_tab_name: Filter for tab name
2. woocommerce_make_offer_form_tab_title: Filter for tab title
3. aeofwc_offer_form_top_message: Filter for text above form
4. aeofwc_offer_form_bottom_message: Filter for text below form

I have removed following filters because of not required:
1. aeofwc-offer-form-intro-html
2. woocommerce_make_offer_form_name
3. woocommerce_make_offer_form_action
4. aeofwc-offer-form-outro-html

Please update the doc as needed.
