### ISSUE TITLE
CSS Conflict

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#268]
* https://www.angelleye.com/support/scp/tickets.php?id=864

User reports that version 1.3.0 was fine, but 1.3.1 is causing a CSS conflict with his theme.

**Comment by mdrahul** [comment]
This bug is due to theme and not due to our plugin. There is one CSS causing this issue.

In http://localhost/angell/wp-content/themes/mediacenter/style.min.css?ver=2.3.5, there is following CSS.
.entry-content li.product .product-inner > a, .products div.product .product-inner > a, li.product .product-inner > a {
    display: block;
    padding: 34.05px;
}

It should be as following:
.entry-content li.product .product-inner > a:first-child, .products div.product .product-inner > a:first-child, li.product .product-inner > a:first-child {
    display: block;
    padding: 34.05px;
}

Let me know if this resolves an issue or not.

**Comment by angelleye** [comment]
So why is it only a problem with our latest release?

**Comment by mdrahul** [comment]
The issue is still there for version 1.3.0. This is common CSS apply to each anchor tag for each product in shop page. So in 1.3.0 the add to cart button is affected and in the latest version the make offer button is affected. This is only due to  CSS by theme. See attached screenshot for both the version.

Version 1.3.0:
![ver_1 3 0](https://cloud.githubusercontent.com/assets/22492841/21762786/a2c171a4-d680-11e6-86b7-6d4a6155fbd8.png)

Version 1.3.1:
![ver_1 3 1](https://cloud.githubusercontent.com/assets/22492841/21762787/a2c53988-d680-11e6-8d8a-f5a45eb40c5e.png)

**Comment by angelleye** [comment]
I'm confused.  I've never had any reports of this being a problem at all until we released the latest updates, and the user the reported says he can switch to 1.3.0 and it looks fine, but when he switches to 1.3.1 it breaks.  He acts like it's easily reproducible by switching back and forth between those versions.

**Comment by angelleye** [comment]
What theme is this that you're showing screenshots from?

**Comment by mdrahul** [comment]
I have activated the theme provided by the client. This is due to incorrect CSS of theme and not due to our plugin.

**Comment by angelleye** [comment]
Okay, I'll check back with the user that reported this for clarification about what they're seeing.

**Comment by angelleye** [comment]
Again, user has verified that 1.3.0 works perfectly fine for him, but 1.3.1 breaks.  He can switch back and forth and reproduce the issue at will.

It seems that something we did in 1.3.1 caused this.

**Comment by angelleye** [comment]
Here is the theme the user is using.  Not sure what you were testing with before, @mdrahul ..??
[themeforest-9177409-mediacenter-electronics-store-woocommerce-theme-wordpress-theme (1).zip](https://github.com/angelleye/offers-for-woocommerce/files/705085/themeforest-9177409-mediacenter-electronics-store-woocommerce-theme-wordpress-theme.1.zip)

**Comment by mdrahul** [comment]
I have tried version 1.3.0 and also 1.2.2 to reproduce the case. I see that in all the version it breaks. I was already testing in the theme you have provided. I have also tested with the theme you have provided in the last comment but I am not able to see the back and forth from my side.

**Comment by angelleye** [comment]
@mdrahul I'm confused here.  You say you were able to see that it breaks...but then you say you can't see the back and forth.  I'm not sure what you mean..??

**Comment by mdrahul** [comment]
I have tried different ways for this and I have found that theme is removing the default WooCommerce function from hook and adding its own function. We need to keep the standard code for all the themes and plugins but if any theme is doing the same with the different way then I think they need to customize our plugin accordingly. So in the case of the displaying offer button in shop page we are using the default hook from WooCommerce and theme is using its own which is causing an issue. If possible can you please ask user to try the dev version on which we have made some major changes related to offer button and if it resolves an issue or not? Also, If possible can we have screenshots of same page for both versions 1.3.0 and 1.2.2 so that I can investigate more?

I have also tried to add our make offer button in the hook provided by them but our offer button overrides the default add to cart button so users will see our make offer button instead of the add to cart. This is due to CSS by theme as they are managing it using position. Like in the screenshot below:

![add-to-cart-button](https://cloud.githubusercontent.com/assets/22492841/23210376/4ab1ad24-f923-11e6-9875-1c9aeaf32cf0.png)

If you see in the screenshot, our make offer button is hiding the add to cart button behind it due to the CSS of the theme. I have changed background color to gray for offer button so you can see that the add to cart button is hidden behind it. See the green color around the offer button.

Let me know your inputs regarding this.

**Comment by angelleye** [comment]
Ok, I can accept that if we're following correct standards.  I'll close the ticket.
