### ISSUE TITLE
Potential theme conflict..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#282]
* https://www.angelleye.com/support/scp/tickets.php?id=960

>Hello, the offer for woocommerce plugin is glitching. It make a duplicate of the make a offer button and add to cart button.
I sent the theme and marketplace plugin. I talk to someone and they said sent the theme, and the marketplace.

[onesocial-child.zip](https://github.com/angelleye/offers-for-woocommerce/files/796431/onesocial-child.zip)
[buddyboss-marketplace.zip](https://github.com/angelleye/offers-for-woocommerce/files/796430/buddyboss-marketplace.zip)

**Comment by mdrahul** [comment]
We need parent onesocial theme to setup this in our local and trace the issue. Can you please provide us the parent theme so that we can move forward?

**Comment by angelleye** [comment]
Yeah, I noticed that.  I just sent them a response asking them to provide that.

**Comment by mdrahul** [comment]
Ok so we need to wait till they provide us the main theme.

**Comment by tejasm-itpath** [comment]
@angelleye @iMansoorAliKhan  I have tested this issue with OneSocial Parent theme and child theme 
+ buddyPress plugin + WC Vendors Plugin and Our Offers for Woocommerce plugin. 
I think this is the issue that we have already fixed in our extension of the Offers plugin. 
Right now I can not reproduce such type of error with Make Offer. I have tested & it is working perfect.
