### ISSUE TITLE
WC vendore Pro - compatibility

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/offers-for-woocommerce#297]
Client's issue

> 1.) when I got the email that an offer was made I clicked the Manage Offer button in that email and it took me to the dashboard page but did not auto select the Manage Offers tab…AND when i clicked the manage offers tab nothing happens…. no data to see. no offers show… just the dashboard.

https://www.angelleye.com/support/scp/tickets.php?id=1012

**Comment by angelleye** [comment]
@tejasm-itpath I don't think you got this quite right.  You're checking for WC Vendors && WC Vendors Pro, but you aren't checking if our Offers for Woo WC Vendors extension is also active.  We only want to make this change if they're WC Vendors Pro as well as our WC Vendors extension.  What we've done here would make it so that they don't even have to buy our extension, which is not what we want, of course.
