### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#311]
* https://wordpress.org/support/topic/some-features-needed/

>1. changing number format : my site using KRW and there should be no decimal so I removed decimal. It would be nice if all number format follows the base currency of woocommerce in next update.
>2. adding pagination to offer list in my account page : no pagination yes headache. I added jquery pagination manually.

> **ask – critical**
>There is no limitation for submitting an offer. An user can submit an offer, refresh the page, submit another offer for the same product, refresh the page, submit another offer for the same product ,,,,,, It would be huge spam…
I think there should be a limitation that an user can only submit an offer if the offer is new or previous offer is expired/completed.

>I want to make that limitation but don’t know where to start..

**Comment by tejasm-itpath** [comment]
@angelleye  I have added Price formatted same as Woocommerce Price. 
Now question is about Pagination , If I go with datatable ajax pagination then Filter about the column will be not usefull. 
Also I have to change lots of code with the query  because right now all the values fetched as get_post_meta.

**Comment by tejasm-itpath** [comment]
@angelleye  
If pagination is necessary then I can change it with Datatables.
