### ISSUE TITLE
Need to Handle Variable Products

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#32]
Need to make offers work for variable products (down to the variable ID / sku).    Need to make sure line item details get passed correctly for these types of offers in order to create the order successfully.

Haven't really done any testing on this at all to this point, so we'll just have to play with it before we get started on this.

**Comment by kcwebmedia** [comment]
Needs to handle multiple attributes.
All 'required' child attributes on variant product single display need to be considered if toggle with jq on the red error message 'you must pick an option'. (so that the form is hidden if you haven't filled out enough to see the add to cart button either.
... I wonder if there is a function for this in WC?
