### ISSUE TITLE
hide include shipping in admin settings

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#321]
Feature Request: 

> As a suggestion for future updates, please consider 'hide include shipping' as an option in general settings so the admin can determine if the vendors can use this feature in their vendor dashboard.
> Reason: the WC vendor Pro shipping functions as a standalone, so vendors may not receive their shipping charge if any third-party shipping is used i.e in this case offers for woocommerce shipping or woocommerce shipping.

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  
Not getting exactly what is the effect of the  'hide include shipping'  option is checked.

**Comment by iMansoorAliKhan** [comment]
@tejasm-itpath , That was the only information client shared,

**Comment by angelleye** [comment]
@tejasm-itpath This may be something we need to do in the WC Vendors extension of ours (or maybe there and here as well if we need a hook or something.)

In our Offers for WooCommerce plugin there is an option to "include shipping" in your response.  For example, if somebody submits an offer for $100 and you accept it without checking "include shipping", then it's going to charge $100 + shipping when they checkout.  If you do check "include shipping" when you accept (or counter) the offer, then it would do $100 without charging anything extra for shipping during checkout.

This user is using our WC Vendors extension for Offers, and he wants to hide this "include shipping" option from the vendors on his site selling items.  

So really this option would need to be added by the WC Vendors extension, but again, we might need to add a hook in the main/base plugin in order to make this function properly.

So the final result would be that the WC Vendors plugin has an option to "Disable the 'include shipping' option for vendors."

We could actually do this for the other options as well, like setting the expiration date, etc.  So...it would probably make sense if we have a section in our WC Vendors settings panel labeled "Vendor Options" and within this the site owner can enable/disable the different features that they want to have available for their vendors.

Does that all make sense?

**Comment by tejasm-itpath** [comment]
@angelleye 
Yes , I got this.
