### ISSUE TITLE
UI/UX issue

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#334]
![image](https://user-images.githubusercontent.com/11312949/29304076-878679a4-81aa-11e7-9433-9478c9f1b20a.png)

Theme : The7

**Comment by MansoorAliKhanOfficial** [comment]
![image](https://user-images.githubusercontent.com/11312949/29304120-ca7f882c-81aa-11e7-84eb-9ffa6b98260c.png)


Also offer sent successfully but no message displayed. it was working before.

**Comment by tejasm-itpath** [comment]
@angelleye  @MansoorAliKhanOfficial 
I have tested in Storefront Theme and Divi Theme. Both the theme doesn't have Issues mentioned above.
Can you provide this theme or Theme name (If it is free). I think this issue is related to particular theme.
If we can get theme then we can check and solve the issue by doing some console.logs in Js.

**Comment by MansoorAliKhanOfficial** [comment]
@tejasm-itpath this theme I m using is the7 multipurpose theme, if you need to test you can check on my test site clients.mansooralikhan.com/blogger/wp-admin

**Comment by tejasm-itpath** [comment]
Okay thanks @MansoorAliKhanOfficial

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan  
It was issue in the margin of the input field , I have fixed it by adding margin to css file 
Check the screenshot for **the7** theme https://www.screencast.com/t/kNEpCkBOaO
