### ISSUE TITLE
Question for wc vendors extension

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/offers-for-woocommerce#335]
I have WC Vendors plugin installed (not pro version) now I purchased your offers for woocommerce - wc vendor plugin because it is compatible for vendors, the problem is when I login into vendors I am not seeing any manage offer tab in vendor dashboard please help me I need to get it done tomorrow.

**My question**:
whats options are available if someone buys our plugin ( WC vendors extension I mean) and use it with free version of WC vendors? Whats the difference?

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial To my knowledge the WC Vendors Pro version is what adds the front-end dashboard.  This page shows the Pro features:  https://www.wcvendors.com/product/wc-vendors-pro/

So it says "Pro Dashboard".  I guess free may provide a simplified dashboard, but Pro would be necessary for more vendor data available on that front-end dashboard.

So if they're using the free version of WC Vendors then our Offers extension should work for sending the offer notifications to the vendor instead of the site owner, but they would have to manage through the WP admin panel instead of a front end dashboard.

This is something else I would ask you to test out for us.  Have you installed WC Vendors (free) + Offers for Woo + Offers WC Vendors to see how it works that way?

**Comment by MansoorAliKhanOfficial** [comment]
@angelleye , Yeah I have installed it on my test site and you re right free version is very much limited, and I dont think there are much options in free version . so the best would be to refer them to WC vendors site and their documentation to read more about it. 

Moreover, a question, is there any messaging system in our plugin where both of them can talk/negotiate for the offer and counter offer to make it final?

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial Not sure I understand your question.  Who do you mean by "both of them"?  Of course, the whole point of the plugin is to be able to counter-offer back and forth, so I'm not sure what you're asking here..??

**Comment by MansoorAliKhanOfficial** [comment]
@angelleye Sorry for the confusion, Actually it's like negotiating over a chat system rather sending counter offers ...

**Comment by angelleye** [comment]
No, that is not something we have enabled right now.  There are plenty of other chat plugins available where people could implement such a thing if they want to.  I'm going to go ahead and close this issue now.
