### ISSUE TITLE
Order Quantity Not Decreased When Offer Accepted

### ISSUE THREAD

**Issue by digitsoft** [angelleye/offers-for-woocommerce#346]
My products are all quantity of 1, but the order quantity is never decreased to 0 when an offer is accepted.

**Comment by angelleye** [comment]
@digitsoft I'm sorry for the delay responding.

This is actually by design because when an offer is accepted that doesn't necessarily mean it's been purchased.  If you accept an offer for $50, for example, but then somebody else shortly after simply buys it at your regular price of $70, that would be good, right?  Well, for you anyway.

The person who got your accepted offer would find that the item was no longer available when they try to purchase, so of course this would be a bad experience for them.  

Some sellers like to leave that possibility open because they don't want to miss out on opportunities if they accept an offer but then that person takes a long time (or never) completes the purchase.  Others may not want to do that because they don't want people to get upset when their item is gone after you accepted their offer.

I think what we need to do here is add an option so site admins can choose which way to handle this.  What's your opinion on that?
