### ISSUE TITLE
Vendors pro : Offers options not showing with default product form set to SIMPLE

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#360]
https://www.angelleye.com/support/scp/tickets.php?id=1576
When we have Vendors pro enabled then in their product form tab we have the option to set default product form to be SIMPLE or Download/virtual, In SIMPLE Product case they are hiding some options which is why offers tab also gets hidden. 
I think we need to make a check for this so that if the form is set to simple then we need show offers tabs, although right now it's not showing. Or may be need to write WC vendors pro for this.
**Normal form loads like this : http://prntscr.com/hf17kt**
**Default form set to simple shows this: http://prntscr.com/hf19tm**

**Comment by tejasm-itpath** [comment]
Hello @digitalchild  , @angelleye  , @iMansoorAliKhan 
Please see this video that give you exact idea of the issue we faced.
https://www.screencast.com/t/2nAMGYLUP

Under Woocommerce setting -> WCvendors setting there is  **Product form tab** and inside that we can set **Default Product Form** for Vendors.
When the Default Product Form is set to **Standard** it is showing Product tabs in Add product form.
But when Default Product Form is set to **Simple Product** ,no products tabs is there.
I have looked into the and code  found that in template file **\wc-vendors-pro\templates\dashboard\product-simple.php** 
there is no code for products tabs that's why it is not showing to front end.
We have our Offers tabs with product meta tabs so it is also hiding Offers tabs too for the product.

**Comment by tejasm-itpath** [comment]
As discuss with @digitalchild
> yes the simple product doesn't have any tabs which is why you can't hook offers in.
>that's the whole point of the simple product form
So @angelleye  If we still wants to add Offers tab there then we can give one checkbox about Enable Offer for that product after product SKU field.
What's your thoughts about it @angelleye @iMansoorAliKhan   ?

**Comment by iMansoorAliKhan** [comment]
@tejasm-itpath  Yeah, I think that would be good to add it here when the form is set to simple.

**Comment by iMansoorAliKhan** [comment]
Any Update here??

**Comment by angelleye** [comment]
This is being completed in the WC Vendors extension 1.0.5 update.
