### ISSUE TITLE
Phone number field Should accept numeric values only

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/offers-for-woocommerce#362]
https://wordpress.org/support/topic/limit-phone-number-to-10-digits-only/

The offer form Phone number is type="text" which accepts any type of input although we know it should be numeric only.

Please check and make necessary adjustments.
Thanks!

**Comment by angelleye** [comment]
@tejasm-itpath I think we should do this a little bit differently.  Validating to only allow 10 characters could confuse people trying to enter values like 555-555-5555, which is 12 characters total.  Instead, I think we should add the validation, but make it so that it always uses the same format...a phone number format.  There should be validation for phone numbers specifically built in to most validation tools.

So, for example, if they type something like 555.555.5555 it would automatically switch it to 555-555-5555.  Or if they just enter 5555555555 then it would add the dashes to format it more nicely.
