### ISSUE TITLE
Counter from buyer should be set back to pending.

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#74]
When buyers submit a counter it's leaving it set as "countered" state, but then there's no easy way to see that it needs attention.

Need to go ahead and set these back to a pending state so that the site owner realizes they need to address it.

**Comment by angelleye** [comment]
If in a pending state, though, links in the buyer email to "click to buy" won't work anymore.  Need to look into this.

**Comment by angelleye** [comment]
When a buyer submits a counter offer it should not override values, but instead, set different post meta values and flag the offer as "buyer countered" somehow.

**Comment by kcwebmedia** [comment]
YES 
* Create new post status for it.
* Add the new post status to other WP Filters that are breaking down queries/args/posts by post_status
* Add logic - if buyer-countered-offer, then OK to add offer to cart (this would add offer to cart at the 'countered' aka 'current' aka 'offer_price')
* On buyer counter offer submit (if parent offer id), then store offer qty/price/amount values as 'buyer-countered' specific 'postmeta' values.
* Manage Offer - If currently 'buyer-countered-offer', then 'post_status' select input needs to have empty <option> html that is also selected='selected' so that the admin is forced to pick from [accept,decline,counter,completed]
