### ISSUE TITLE
General Settings - Enable/Disable

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#78]
The check boxes for show/ide don't seem to be having any effect.  The button is showing up in all areas regardless of the option.

**Comment by angelleye** [comment]
These should override product specific settings.

**Comment by kcwebmedia** [comment]
**We probably don't even need a global setting for "Enable Make Offer button on single product page"** -- Because the option should be On/Off at the product level. AND you would never have make offer buttons show on the frontpage or archives if they were globally turned off on all single product views. 

Furthermore, if admin wanted the offers to not show globally then we would need a global 'enable/disable all offer buttons'.

**Do you agree with this?**
* Remove 'Enable Make Offer button on single product page" (Plugin Options Page)
* Add "Disable Make Offer button"  (Plugin Options Page)
 * This checkbox would allow the store admin to still accept reject offers, and still allows accepted offers to be purchased... just hides all of the buttons for any products that have it enabled. (Like an 'out to lunch' toggle).

**Comment by kcwebmedia** [comment]
This also fixed issue #79

**Comment by kcwebmedia** [comment]
Found some testing code that was left in echo statement; Removed it
